"""
Django settings for suchai_webinterface project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from dotenv import load_dotenv
import os
from pathlib import Path

from apps import accounts
from apps.accounts import mongo_logging_middleware
from apps.accounts.mongo_logging_middleware import MongoLoggingMiddleware

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# Determine if debug mode should be enabled based on an environment variable
# DEBUG = os.getenv('DJANGO_DEBUG', 'True')
DEBUG = True
print(f"DEBUG: {DEBUG}")

if DEBUG:
    # Use an insecure secret key for development
    SECRET_KEY = 'django-insecure-yg^om13za-@h6=ylvtlvb7u-iik5ecruxj%de=h)a1_@7stkuv'
else:
    # Read the secret key from an environment variable for production
    SECRET_KEY = os.environ['SECRET_KEY']

ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = ["http://localhost:8000", "https://*.ngrok-free.app"]

# Application definition

load_dotenv()

PERSONALITY = {
    'mission_name': os.environ['MISSION_NAME'],
    'entity_name': os.environ['ENTITY_NAME'],
    'fake_web_git_repo_url': os.environ['FAKE_WEB_GIT_REPO_URL'],
    'mission_logo_url': os.environ['MISSION_LOGO_URL'],
    'ground_station_lat': os.environ['GROUND_STATION_LAT'],
    'ground_station_lon': os.environ['GROUND_STATION_LON'],
    'satellite_name_TLE': os.environ['SATELLITE_NAME_TLE'],
    'mission_real_manual_url': os.environ['MISSION_REAL_MANUAL_URL'],
    "logo_style": os.environ['LOGO_STYLE'],
    "FAKE_DOCS_V2_URL": os.environ['FAKE_DOCS_V2_URL'],
    'developer_name_1': os.environ['DEVELOPER_NAME_1'],
    'developer_name_2': os.environ['DEVELOPER_NAME_2'],
}

# print(f"PERSONALITY: {PERSONALITY}")

INSTALLED_APPS = [
    'apps.accounts.apps.AccountsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'apps.accounts.mongo_logging_middleware.MongoLoggingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'suchai_webinterface.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'suchai_webinterface.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
